spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shortener}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  base-url: http://localhost:8080
  own-host: localhost
  snowflake:
    worker-id: 0
  redis:
    url-ttl-seconds: 86400
    not-found-ttl-seconds: 300

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: swiftlink

logging:
  level:
    org.example: INFO
    org.hibernate.SQL: WARN
    liquibase: INFO
